r"""
Confirms a piece's counterexamples against the FULL model.

A piece over-approximates (see abstraction.py), so some of its
counterexamples may rely on an abstracted step the real model can't take.
To tell them apart, every counterexample is re-executed on the full,
unmodified model, constrained so that at each step the full model's state,
projected onto the piece's variables, must equal the counterexample's next
state (steps that only change hidden variables are allowed in between).

All counterexamples of one piece are checked in a single TLC run: the
replay module picks a trace index nondeterministically in Init, and TLC
reports every index whose trace can be followed to the end. The search is
small because the visible half of the state is pinned at every step; only
the hidden variables still vary.

Replay runs in two rounds. The *strict* round requires every full-model
step to advance the trace (hidden variables may only change together with
a visible step); it is cheap and confirms almost everything. Only traces it
cannot confirm go to the *permissive* round, which also allows steps that
change hidden variables alone -- needed when an abstracted guard must first
be made true by another piece's actions, but it lets every other piece's
state roam, so it is the expensive one and may hit the budget.

A finding whose traces all fail to replay is NOT discarded: TLC reports the
shortest path to each violating state, and a different path to the same
state might have replayed. Such findings are reported as "unconfirmed" so
nothing is silently dropped (a false negative is the costly error here).
"""
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Set

from src.tla.cfg import TLCConfig
from src.tla.sany_ast import Model
from src.tla.tools import TLCResult, TraceState, run_tlc

_ID = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
_RESERVED = {"TRUE", "FALSE", "BOOLEAN", "STRING", "Nat", "Int"}


@dataclass
class ReplayOutcome:
    confirmed: Set[int]                 # indices into the traces list
    full_traces: Dict[int, List[TraceState]]   # concrete full-model trace per confirmed index
    tlc: TLCResult


def _model_values(cfg: TLCConfig, model: Model) -> List[str]:
    """Bare identifiers on the right-hand side of the CONSTANTS block that
    are not operators of the module: TLC model values. They show up as bare
    names in counterexamples and must be declared to be written back."""
    known = set(model.constants.values()) | {d.name for d in model.defs.values()}
    vals = set()
    for line in cfg.constants_text.split("\n"):
        if "=" in line and "<-" not in line:
            rhs = line.split("=", 1)[1]
            rhs = re.sub(r'"[^"]*"', " ", rhs)
            for tok in _ID.findall(rhs):
                if tok not in known and tok not in _RESERVED and not tok.isdigit():
                    vals.add(tok)
    return sorted(vals)


def replay(model: Model, cfg: TLCConfig, init_name: str, next_name: str,
           visible: List[str], traces: List[List[TraceState]], work_dir: Path,
           max_states: int, timeout: int, allow_hidden_steps: bool = True) -> ReplayOutcome:
    name = f"{model.module_name}__Replay"
    work_dir.mkdir(parents=True, exist_ok=True)
    mvals = _model_values(cfg, model)
    all_vars = sorted(model.variables.values())

    def rec(st: TraceState) -> str:
        return "[" + ", ".join(f"{v} |-> {st.values[v]}" for v in visible) + "]"

    traces_txt = ",\n    ".join(
        "<<" + ", ".join(rec(s) for s in t) + ">>" for t in traces)
    lens = ", ".join(str(len(t)) for t in traces)

    hidden_step = ("       \\/ /\\ replay__Proj' = replay__Proj\n"
                   "          /\\ replay__i' = replay__i\n") if allow_hidden_steps else ""
    text = f"""---- MODULE {name} ----
\\* AUTO-GENERATED by src.decomposition.replay -- do not edit.
EXTENDS {model.module_name}, Naturals, TLC
{"CONSTANTS " + ", ".join(mvals) if mvals else ""}
VARIABLES replay__i, replay__k

replay__T == <<
    {traces_txt}
  >>
replay__L == <<{lens}>>
replay__Proj == [{", ".join(f"{v} |-> {v}" for v in visible)}]

replay__Init ==
    /\\ replay__k \\in 1..{len(traces)}
    /\\ replay__i = 1
    /\\ {init_name}
    /\\ replay__Proj = replay__T[replay__k][1]

replay__Next ==
    /\\ {next_name}
    /\\ UNCHANGED replay__k
    /\\ \\/ /\\ replay__i < replay__L[replay__k]
          /\\ replay__Proj' = replay__T[replay__k][replay__i + 1]
          /\\ replay__i' = replay__i + 1
{hidden_step}
replay__Spec == replay__Init /\\ [][replay__Next]_<<replay__i, replay__k, {", ".join(all_vars)}>>

replay__NotReached == replay__i < replay__L[replay__k]
====
"""
    # The replay module EXTENDS the original, so it must sit next to it.
    for f in model.tla_path.parent.glob("*.tla"):
        (work_dir / f.name).write_text(f.read_text(encoding="utf-8"), encoding="utf-8")
    (work_dir / f"{name}.tla").write_text(text, encoding="utf-8")
    consts = cfg.constants_text
    if mvals:
        consts = consts.rstrip() + "\n" + "\n".join(f"    {v} = {v}" for v in mvals)
    # The full model is explored under its own invariants as constraints
    # (see run_tlc's stop_at_violations), so a trace only replays if every
    # state before the last satisfies ALL of the model's invariants -- the
    # same "primary violation" semantics the pieces and the full run use.
    rcfg = TLCConfig(specification="replay__Spec", constants_text=consts,
                     invariants=["replay__NotReached"],
                     constraints=list(cfg.invariants) + list(cfg.constraints),
                     action_constraints=list(cfg.action_constraints), check_deadlock=False)
    (work_dir / f"{name}.cfg").write_text(rcfg.render(), encoding="utf-8")

    res = run_tlc(work_dir / f"{name}.tla", work_dir / f"{name}.cfg",
                  max_states=max_states, timeout=timeout, collect_all=True,
                  check_deadlock=False, stop_at_violations=False,
                  group_by=lambda v: v.trace[-1].values.get("replay__k") if v.trace else None,
                  traces_per_group=1)
    confirmed: Set[int] = set()
    full: Dict[int, List[TraceState]] = {}
    for v in res.violations:
        if not v.trace:
            continue
        k = int(v.trace[-1].values.get("replay__k", "0")) - 1
        if k >= 0 and k not in confirmed:
            confirmed.add(k)
            full[k] = [TraceState(s.action, {x: y for x, y in s.values.items()
                                              if not x.startswith("replay__")})
                       for s in v.trace]
    return ReplayOutcome(confirmed, full, res)
